Pages/BookList/Create.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication.Models;

namespace WebApplication.Pages.BookList
{
    public class Create : PageModel
    {
        private readonly DbContextDatabase _database;

        public Create(DbContextDatabase database)
        {
            _database = database;
        }
        
        [BindProperty]
        public Books Books { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                //validar que estan todos los campos completados guardat y redireccionar
                await _database.Bookses.AddAsync(Books);
                await _database.SaveChangesAsync();
                return RedirectToPage("Index");
            }
            else
            {
                return RedirectToPage();
            }
        }
        
    }
}

Pages/BookList/Edit.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication.Models;

namespace WebApplication.Pages.BookList
{
    public class Edit : PageModel
    {
        private DbContextDatabase _database;
        public Edit(DbContextDatabase database)
        {
            _database = database;
        }
        [BindProperty] 
        public Books Books { get; set; }

        public async Task OnGet(int id)
        {
            Books = await _database.Bookses.FindAsync(id);
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                //validar campo y buscar en la base de datos el id del libro
                var updateBooks = await _database.Bookses.FindAsync(Books.Id);
                updateBooks.Author = Books.Author;
                updateBooks.NameBook = Books.NameBook;
                updateBooks.ISBN = Books.ISBN;
                await _database.SaveChangesAsync();
                return RedirectToPage("Index");
            }
            else
            {
                return RedirectToPage();
            }
        }
    }
}

Pages/BookList/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApplication.Models;

namespace WebApplication.Pages.BookList
{
    public class Index : PageModel
    {
        private readonly DbContextDatabase _database;

        public Index(DbContextDatabase database)
        {
            _database = database;
        }
        public IEnumerable<Books> Bookses { get; set; }
        
        public async Task OnGet()
        {
            Bookses = await _database.Bookses.ToListAsync();
        }

        public async Task<IActionResult> OnPostEliminar(int id)
        {
            //buscar el id en la base de datos y 
            var deleteBooks = await _database.Bookses.FindAsync(id);
            if (deleteBooks != null)
            {
                _database.Bookses.Remove(deleteBooks);
                await _database.SaveChangesAsync();
                return RedirectToPage("Index");
            }
            return NotFound();
        }
    }
}

Pages/BookList/Upsert.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApplication.Models;

namespace WebApplication.Pages.BookList
{
    public class Upsert : PageModel
    {
        private DbContextDatabase _database;
        public Upsert(DbContextDatabase database)
        {
            _database = database;
        }
        [BindProperty] 
        public Books Books { get; set; }

        public async Task<IActionResult> OnGet(int? id)
        {
            Books = new Books();
            if (id == null)
            {
                return Page();
            }
            Books = await _database.Bookses.FirstOrDefaultAsync(data => data.Id == id);
            if (Books == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                //validar campo y buscar en la base de datos el id del libro
                if (Books.Id == 0)
                {
                    _database.Bookses.Add(Books);
                }
                else
                {
                    _database.Bookses.Update(Books);
                }
                
                /*var updateBooks = await _database.Bookses.FindAsync(Books.Id);
                updateBooks.Author = Books.Author;
                updateBooks.NameBook = Books.NameBook;
                updateBooks.ISBN = Books.ISBN;*/
                
                await _database.SaveChangesAsync();
                return RedirectToPage("Index");
            }
            else
            {
                return RedirectToPage();
            }
        }
    }
}

Pages/BookList/Create.cshtml
@page
@model WebApplication.Pages.BookList.Create
<div class="border container p-3">
    <form method="post">
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Books.Author"></label>
            </div>
            <div class="col-5">
                <input asp-for="Books.Author" class="form-control"/>
            </div>
            <span asp-validation-for="Books.Author" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Books.NameBook"></label>
            </div>
            <div class="col-5">
                <input asp-for="Books.NameBook" class="form-control"/>
            </div>
            <span asp-validation-for="Books.NameBook" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Books.ISBN"></label>
            </div>
            <div class="col-5">
                <input asp-for="Books.ISBN" class="form-control"/>
            </div>
            <span class="text-danger" asp-validation-for="Books.ISBN"></span>
        </div>
        <div class="form-group row">
            <div class="col-2 offset-4">
                <input value="Create" type="submit" class="btn btn-success form-control"/>
            </div>
            <div class="col-2">
                <a asp-page="Index" class="btn btn-success form-control">Regresar</a>
            </div>
        </div>
    </form>
</div>

@section Scripts
{
    <partial name="Shared/_ValidationScriptsPartial"/>
}

Pages/BookList/Edit.cshtml
@page
@using WebApplication.Models
@model WebApplication.Pages.BookList.Edit

<div class="border container p-3">
    <h3>Editar Información</h3>
    <form method="post">
        <input type="hidden" asp-for="Books.Id"/>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Books.Author"></label>
            </div>
            <div class="col-5">
                <input asp-for="Books.Author" class="form-control"/>
            </div>
            <span asp-validation-for="Books.Author" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Books.NameBook"></label>
            </div>
            <div class="col-5">
                <input asp-for="Books.NameBook" class="form-control"/>
            </div>
            <span asp-validation-for="Books.NameBook" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Books.ISBN"></label>
            </div>
            <div class="col-5">
                <input asp-for="Books.ISBN" class="form-control"/>
            </div>
            <span class="text-danger" asp-validation-for="Books.ISBN"></span>
        </div>
        <div class="form-group row">
            <div class="col-2 offset-4">
                <input value="Actualizar" type="submit" class="btn btn-primary form-control"/>
            </div>
            <div class="col-2">
                <a asp-page="Index" class="btn btn-success form-control">Regresar</a>
            </div>
        </div>
    </form>
</div>

@section Scripts
{
    <partial name="Shared/_ValidationScriptsPartial"/>
}

Pages/BookList/Index.cshtml
@page
@using System.Linq
@model WebApplication.Pages.BookList.Index


<div class="container row p-0 m-0 col-12">
    <div class="col-9">
        <h3 class="text-info">Lista de Libros</h3>
    </div>
    <div class="col-3">
        <a asp-page="Upsert" class="btn btn-info form-control">Agregar libros</a>
    </div>
    <!--<div class="col-12 border p-3">
        <form method="post">
            @if (Model.Bookses.Count() > 0)
            {
                <table class="table table-striped border">
                    <tr class="table-secondary">
                        <th>
                            <label asp-for="Bookses.FirstOrDefault().NameBook"></label>
                        </th>
                        <th>
                            @Html.DisplayNameFor(data => data.Bookses.FirstOrDefault().Author)
                        </th>
                        <th>
                            <label asp-for="Bookses.FirstOrDefault().ISBN"></label>
                        </th>
                        <th>
                            <label>Eliminar / Editar</label>
                        </th>
                    </tr>
                    @foreach (var item in Model.Bookses)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(m => item.NameBook)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.Author)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.ISBN)
                            </td>
                            <td>
                                <button asp-page-handler="Eliminar" 
                                        asp-route-id="@item.Id" 
                                        onclick="return confirm('¿Seguro de eliminar?')" class="btn btn-danger btn-sm">Eliminar</button>
                            
                                <a asp-page="Edit" 
                                   asp-route-id="@item.Id" 
                                   class="btn btn-success btn-sm">Editar</a>
                            </td>
                        </tr>
                    }
                </table>
            }
            else
            {
                <p> No hay libros</p>
            }    
        </form> 
    </div> -->
    
    <div class="col-12 mt-5">
        <table id="myTable" class="table table-striped table-bordered" style="width: 100%">
            <thead>
            <tr>
                <th>namebook</th>
                <th>author</th>
                <th>isbn</th>
                <th>Actualizar</th>
            </tr>
            </thead>
        </table>
    </div>
</div>
@section Scripts
{
     <script src="~/js/bookList.js"></script>
}

Pages/BookList/Upsert.cshtml
@page
@model WebApplication.Pages.BookList.Upsert

<div class="border container p-3">
    <h3> @(Model.Books.Id!=0? "EDITAR" : "CREATE" ) </h3>
    <form method="post">
        @if (Model.Books.Id != 0)
        {
            <input type="hidden" asp-for="Books.Id"/>
        }
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Books.Author"></label>
            </div>
            <div class="col-5">
                <input asp-for="Books.Author" class="form-control"/>
            </div>
            <span asp-validation-for="Books.Author" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Books.NameBook"></label>
            </div>
            <div class="col-5">
                <input asp-for="Books.NameBook" class="form-control"/>
            </div>
            <span asp-validation-for="Books.NameBook" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Books.ISBN"></label>
            </div>
            <div class="col-5">
                <input asp-for="Books.ISBN" class="form-control"/>
            </div>
            <span class="text-danger" asp-validation-for="Books.ISBN"></span>
        </div>
        <div class="form-group row">
            <div class="col-2 offset-4">
                <input value="@(Model.Books.Id != 0 ? "Edit": "Crear")" 
                       type="submit" 
                       class="btn btn-primary form-control"
                       />
            </div>
            <div class="col-2">
                <a asp-page="Index" class="btn btn-success form-control">Regresar</a>
            </div>
        </div>
    </form>
</div>

@section Scripts
{
    <partial name="Shared/_ValidationScriptsPartial"/>
}